apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: block-snapshotvol
spec:
  volumeSnapshotClassName: block-snapshotclass
  source:
    persistentVolumeClaimName: csisnaps-pvc-vsan-claim
