apiVersion: v1
kind: Pod
metadata:
  name: csisnaps-restore-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - name: csisnaps-snap
      mountPath: "/snapshot"
    command: [ "sleep", "1000000" ]
  volumes:
    - name: csisnaps-snap
      persistentVolumeClaim:
        claimName: block-snapshot-restore

