apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-snapshot-restore
spec:
  storageClassName: csisnaps-sc
  dataSource:
    name: block-snapshotvol
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
