apiVersion: v1
kind: Pod
metadata:
  name: native-pod-busybox
  namespace: demo-ns
  labels:
    app: podvm
spec:
  containers:
  - image: 192.168.182.129/demo-ns/busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
