kind: Pod
apiVersion: v1
metadata:
  name: busybox-simple-with-res
spec:
  containers:
  - name: busybox
    image: 10.203.182.129/demo-ns/busybox:latest
    command: [ "sleep", "1000000" ]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
