apiVersion: v1 
kind: Service
metadata:
  labels: 
    app: nginx2
  name: nginx-svc
  namespace: web2
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
  selector:
    app: nginx2
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: web2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx2 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
