apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx4
  name: nginx-svc
  namespace: web4
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    app: nginx4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: web4
spec:
  selector:
    matchLabels:
      app: nginx4
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
