apiVersion: v1 
kind: Service
metadata:
  labels: 
    app: nginx3
  name: nginx-svc
  namespace: web3
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
  selector:
    app: nginx3
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: web3
spec:
  selector:
    matchLabels:
      app: nginx3
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx3 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
