kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-first-sc
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
  storagepolicyname: "vSAN Default Storage Policy"
  csi.storage.k8s.io/fstype: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-first-pvc
spec:
  storageClassName: my-first-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
